version: 0.0
os: linux
files:
  - source: /
    destination: /var/lib/tomcat8/webapps/
  - source: /var/lib/tomcat8/webapps/*.war
    destination: /var/lib/tomcat8/webapps/ROOT
hooks:
AfterInstall:
  - location: scripts/post_install.sh
    timeout: 300
    runas: root
