heapunderflow:
    image: cadprasad/heapunderflow:latest
    ports:
      - 8100:8080
    links:
      - mysql

mysql:
  image: mysql
  ports:
    - "3307:3306"
  environment:
    - MYSQL_DATABASE=heapunderflow
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
