services:
  heapunderflow:
    image: cadprasad/heapunderflow:latest
    ports:
      - 8100:8080

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=root
